### PR TITLE
Localstorage sketch

### PR DESCRIPTION
**Pull request by sinaghazi**
regarding to #22 
adding the localstorage save and load to the component

### CODE REVIEW

**Comment by ajthinking** [comment]
Thanks for this! I think we want to hold a bit on this because:

* it only fixes storage of the sketch. What about schema, templates, settings, review changes, review discards etc. These things need also be remembered and putting it in the component side like this will get very repetitive and bloat the project.
* localstorage is a blocking action, we dont want to read/write to it every keydown for performance reasons (I actually did that myself in the project but that has now turned to preferences in the vuex store).

This might be an architecture to consider:
Set an interval every x seconds to trigger a serialization of the WHOLE Vuex store/state and save that to localstorage. On page load attempt to fetch that, else resort to defaults. All of this can be taken care of on the store side to keep components clean.

Closing this for now, let me know of what you think.

**Comment by ajthinking** [comment]
Ok, nice to hear you thinking the same @elbojoloco. And good effort by @sinaghazi, appreciate it.

Regarding worst case scenario, what is that? Error writing to local storage?

Also, what is the actual benefit of using localstorage? What about ONLY running "server storage" on interval where the Store is POST:ed to server and put into a JSON file? It might be nice to give the user an actual file that can be commited alongside all the other files in the repo (maybe saved as storage/pipe-dream/project.json). That way the user can share the schema with other users of the repository. That would also be handy for bug reports and integration tests.

Or maybe BOTH localstorage and server JSON is the way to go 🤔

**Comment by elbojoloco** [comment]
With worst case scenario I meant anything really. There are so many cases where it can mess up :)

Storing the configs to a file seems good too, that way it's easier to collaborate on them. Write that down!

**Comment by ajthinking** [comment]
Got it, true that :) OK putting that in the Trello board

**Comment by sinaghazi** [comment]
To have a proper persistence of project work makes sense. I can't agree more with you guys. 

Maybe we can get inspired by how jhipster is doing so on JDL studio https://start.jhipster.tech/jdl-studio/

**Pull request closed without merging**
