### PR TITLE
Expanded a bit on the default factory attribute types

### PR DESCRIPTION
**Pull request by martindilling**
I started out just wanting to replace `rand()` with `random_int()` as that is the recommended way to generate a random integer.
But then I started adding a few more adjustments that would hopefully generate a bit better out of the box.

Disclaimer: Not tested, I just assume I get how this works, and hope I've changed the correct places ;)

### CODE REVIEW

**Comment by martindilling** [comment]
Damn, sorry, I didn't realise I created this branch from my other PR xD

**Comment by ajthinking** [comment]
Wow, thanks for all the PR:s! Really appreciate it :) 

I'll clone this down just to see all works. If I recall correctly the seeders/factories assumes there are related models between IDs 1-10 thats the reason of that strange random range.

Not following the branch issue, if all checks out, its good to merge right?

**Comment by ajthinking** [comment]
Wow, really good. Just one edge case with the IDs. Can you give me some advice on how to do the PR workflow?

I did this
```
fetch origin pull/18/head:pr-18
checkout pr-18
```
Tested it and found something I wanted to add:
```
/* The seeds assumes related models are available with ID in range [1,10] */
if(attribute.foreign) {
     return "random_int(1, 10)"
}
```
Commited that and then:
```
git push --set-upstream origin pr-18
```
But that pushes a new branch to the repo. I would like to add it to this PR. Any ideas how to best do that? If it is easier maybe you can add that piece of code on your side. It's at line ~119.

Cheers :D

**Comment by martindilling** [comment]
Don't have much experience with the whole PR workflow xD
But I added the check :)

**Comment by ajthinking** [comment]
Works like a charm!

**Pull request merged**
