### PR TITLE
Fix newline parsing when generating file in windows

### PR DESCRIPTION
**Pull request by adhikasp**
This fix leftover CRLF ending when generating files in Windows machine.

Add regex in parser logic to strip `\r` and `\n` on beginning and end of line.

### CODE REVIEW

**Comment by adhikasp** [comment]
After further test, the above fix still doesn't fix the bug.

The bug occurs only when copy-pasting text from notepad (or other Windows editor who use CRLF ending).
Writing directly on the web editor doesn't trigger the bug.

**Comment by adhikasp** [comment]
Commit updated.

Force all occurences of CRLF `\r\n` to LF `\n`.

**Comment by robtesch** [comment]
What a winner, I was suffering this exact problem a couple of days ago.

**Comment by ajthinking** [comment]
Thanks @adhikasp 🔥🔥🔥

**Pull request merged**
