### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by mateusjunges**
This package apply some fixes from StyeleCI

### CODE REVIEW

**Comment by ajthinking** [comment]
Thanks @mateusjunges, this is great 😄  May I ask you, how to set checks like that up when developing? Im using VS Code.

**Comment by mateusjunges** [comment]
I have a package on my github accout that have styleci and travisci checks.
you can [check it](https://github.com/mateusjunges/laravel-acl) here.
Basically, you need to  create a `.styleci.yml` file and allow styleci to have access to the repository where you want to add those checks. You can do it [here](https://styleci.io/login). The check occur in every push to your branch, and, if there are some issues, style ci create a pull request fixing it.

For [TravisCI](https://travis-ci.org/) you need a config file, which looks like [this one](https://github.com/mateusjunges/laravel-acl/blob/master/.travis.yml). 

Now, [protect your master branch](https://help.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks), and you will only be able to merge pull requests after pass those checks.

Hope it helps!

**Comment by ajthinking** [comment]
Thanks, appreciate it! Adding this to the TODO list for now (https://trello.com/b/R11mhfdy/pipe-dream)

**Comment by mateusjunges** [comment]
Ok. Contact me if you need help for something!

**Pull request merged**
